# Generated by Django 4.0.1 on 2023-04-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallImageURL', models.URLField()),
                ('largeImageURL', models.URLField()),
                ('shortTitle', models.CharField(max_length=64)),
                ('longTitle', models.CharField(max_length=64)),
                ('mrp', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=64)),
                ('tagline', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
            ],
        ),
    ]
